version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
